config/routes.rb
Trackle::Application.routes.draw do

  resources :announcements, :only => [:create, :index, :edit, :destroy, :update]
  resources :assignments, :except => [:show]
  resources :projects, :except => [:new]
  resources :tasks, :except => [:new]  
  resources :task_groups, :except => [:new, :index]
  devise_for :users
  root :to => 'schedules#show'

  devise_scope :user do
    root :to => "devise/sessions#new"
  end

  resources :users, :only => [:index, :show, :edit, :update, :destroy]
  get "/archive" => "archives#show", :as => "archives"

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base

	belongs_to :user

	validates :content, :presence => true
	validates :user_id, :presence => true
	validates :subject, :presence => true
	validates :end_date, :presence => true


  attr_accessible :begin_date, :content, :end_date, :subject, :user_id

  def self.current
  	Announcement.where('end_date > ?', Time.now)
  end
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
	before_filter :authenticate_user!
	before_filter :parse_params, :only => [:create, :update]
	load_and_authorize_resource
	respond_to :json, :js, :html
	
	def index
		@announcements = Announcement.order('created_at')
		@announcement = current_user.announcements.build(:begin_date => Time.now.strftime("%-m/%d/%Y"), :end_date => 1.day.from_now.localtime.strftime("%-m/%d/%Y"))
	end

	def create
		@announcement = current_user.announcements.build(params[:announcement])
		if @announcement.save
			@announcements = Announcement.order('created_at')
			@notice = "Announcement created"
			respond_with @announcements, @notice
		else
			js_alert(@announcement)
		end
	end

	def edit
		@announcement = Announcement.find(params[:id])
	end

	def update
		@announcement = Announcement.find(params[:id])
		if @announcement.update_attributes(params[:announcement])
			flash[:notice] = "Announcement updated"
			js_redirect_to announcements_path and return
		else
			js_alert(@announcement)
		end
	end

	def destroy
		@announcement = Announcement.find(params[:id])
		if @announcement.destroy
			@notice = "Announcement deleted"
			@announcements = Announcement.order('created_at')
			respond_with @announcements
		end
	end

	private
	def parse_params
		begin_date = params[:announcement][:begin_date] || ""
		end_date = params[:announcement][:end_date] || ""
		params[:announcement][:begin_date] = parsed_date(begin_date) unless begin_date == ""
		params[:announcement][:end_date] = parsed_date(end_date) unless end_date == ""
	end
end

app/views/announcements/_display_index.html.erb
<% if @announcements.count > 0 %>
	<% @announcements.each do |announcement| %>
		<div class="eachAnnouncement">
			<strong><%= "#{announcement.subject}:" %></strong>
			<%= announcement.content %>
			<span id="userTag"><%= "-posted by #{announcement.user.name}" %></span>
			<span><em><%= announcement.begin_date.to_date %></em></span>
			<span class="deleteButton">x</span>
		</div>
	<% end %>
<% end %>

app/views/announcements/_form.html.erb
<%= form_for @announcement, :remote => true do |f| %>
	<div class="announcementFields">
		<%= f.text_field :subject %>
		<%= f.label :subject %>
		<%= f.text_field :begin_date, :class => "datepicker" %>
		<%= f.label :begin_date %>
		<%= f.text_field :end_date, :class => "datepicker" %>
		<%= f.label :end_date %>
	</div>
	<div>
		<%= f.text_area :content %>
		<%= f.label :content %>
	</div>	

		<!-- <#%= f.hidden_field :user_id, :value => current_user.id %> -->
		<%= f.submit %>
		
<% end %>

app/views/announcements/_index.html.erb
<% if @announcements.size > 0 %>
	<% @announcements.each do |announcement| %>
		<div class="editAnnouncement">
			<div>
				<span><%= "#{announcement.subject}"%></span>
				<span><%= "-posted by #{announcement.user.name}" %></span>
				<span><em><%= "Created: #{announcement.created_at.localtime.to_date}" %></em></span>	
				<span><em><%= "Begins: #{announcement.begin_date.localtime.to_date}" %></em></span>	
				<span><em><%= "Ends: #{announcement.end_date.localtime.to_date}" %></em></span>	
			</div>
			<div class="announcementContent">
				<%= announcement.content %></br>					
			</div>
			<div>
				<span>
					<%= link_to "Edit", edit_announcement_path(announcement) %>
				</span> |
				<span>
					<%= link_to "Delete", announcement_path(announcement), :method => :delete, :remote => true, :confirm => "Are you sure you want to delete this announcement?" %>
				</span>
			</div>
				
		</div>
	<% end %>
<% else %>
<p>There are no announcements.</p>	
<% end %>

app/views/announcements/create.js.erb
$('#alerts').html("");
$('#alerts').append('<%= j render "shared/messages", :locals => { :notice => @notice} %>').fadeIn('slow');
setTimeout(function() {
	$('#alerts').fadeOut('slow');
}, 3000);
$('#announcement_subject, textarea').val('');
$('#editAnnouncementList').html('<%= j render "announcements/index" %>');

app/views/announcements/destroy.js.erb
$('#editAnnouncementList').html('<%= j render "index" %>');
$('#alerts').html("");
$('#alerts').append('<%= j render "shared/messages", :locals => { :notice => @notice} %>').fadeIn('slow');
setTimeout(function() {
	$('#alerts').fadeOut('slow');
}, 3000);

app/views/announcements/edit.html.erb
<div id="announcementInterior" class="resourceColumn resourceForm">
	<div id="announcementErrors"></div>
	<%= render 'form' %>	
</div>

app/views/announcements/index.html.erb
<div class="announcementIndex">
	<h2>Announcements</h2>

	<div id="announcements">
		<span>Create Announcement</span>
		<div id="announcementInterior">
			<div id="announcementErrors"></div>
			<%= render 'announcements/form' %>
		</div>
	</div>

	<div id="editAnnouncementList">
		<%= render 'index' %>
	</div>
		
</div>
	