config/routes.rb
Trackle::Application.routes.draw do

  resources :announcements, :only => [:create, :index, :edit, :destroy, :update]
  resources :assignments, :except => [:show]
  resources :projects, :except => [:new]
  resources :tasks, :except => [:new]  
  resources :task_groups, :except => [:new, :index]
  devise_for :users
  root :to => 'schedules#show'

  devise_scope :user do
    root :to => "devise/sessions#new"
  end

  resources :users, :only => [:index, :show, :edit, :update, :destroy]
  get "/archive" => "archives#show", :as => "archives"

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  include ActionView::Helpers::DateHelper

  validates :queue_index, :presence => true

  has_many :comments, :dependent => :destroy
  accepts_nested_attributes_for :comments, :allow_destroy => true, reject_if: proc { |attributes| attributes['content'].blank? }
	belongs_to :user
	belongs_to :task
	belongs_to :project

  attr_accessible :amount_completed, :completed_at, :deadline, 
                  :duration, :hold, :started_at, 
                  :user_id, :task_id, :project_id, :comments_attributes, 
                  :queue_index, :resumed_at, :elapsed_time
  before_save :check_elapsed_time
  before_save :update_queue

  def status
    return "completed" if self.completed_at?
    return "in progress" if started_at && !hold
    return "on hold" if started_at
    "not yet begun"
  end

  def elapsed_time
    return 0.0 if !self.resumed_at
    return read_attribute(:elapsed_time).to_f if self.hold?
    Time.now - self.resumed_at + read_attribute(:elapsed_time)
  end

  def self.incomplete
    incomplete = Assignment.where('completed_at is NULL')
    incomplete.select { |assignment| assignment.project.completed_at.nil? }
  end

  private
  def check_elapsed_time
    if self.hold == true || !!self.completed_at
      self.elapsed_time = Time.now - self.resumed_at + read_attribute(:elapsed_time)
    end
  end

  def update_queue
    if self.completed_at?
      if self.queue_index != 0
        self.update_attributes(:queue_index => 0) 
        self.user.incomplete_assignments.each do |assignment|
          assignment.queue_index -= 1
          assignment.save
        end
      end
    end
  end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  load_and_authorize_resource  
  before_filter :authenticate_user!
	before_filter :parse_date_params, :only => [:create, :update]
	before_filter :check_timestamps, :only => [:update]
	respond_to :js, :html, :json

	def new
		@assignment = Assignment.new(params[:assignment])
		# @queue_index = @assignment.user.assignments.count + 1
		@assignment.comments.build
		respond_with @assignment, @comment, @queue_index
	end

	def index
		@assignments = Assignment.incomplete
		respond_with @assignments		
	end

	def create
		@assignment = Assignment.new(params[:assignment])
		if @assignment.save
			respond_with(@assignment)
		end
	end

	def edit
		@assignment = Assignment.find(params[:id])
	end

	def update
		@assignment = Assignment.find(params[:id])
		@user = @assignment.user
		if @assignment.update_attributes(params[:assignment])
			if params[:commit] == "Update"
				flash[:notice] = "Assignment updated"
				js_redirect_to(root_path) and return
			end
			respond_to do |format|
	      format.js
	      format.json { render :json => { :assignment => Assignment.find(params[:id])} }
	    end
		else
			js_alert(@assignment) and return
		end
	end

	def destroy 
		@assignment = Assignment.find(params[:id])
		@user = @assignment.user
		if @assignment.destroy
			respond_with @user
		end
	end

	private
	def parse_date_params
		parse_dates(params[:assignment]) if params[:assignment]
	end

	def check_timestamps
    params[:assignment][:started_at] = Time.now if params[:assignment][:started_at] == "true"
    params[:assignment][:resumed_at] = Time.now if params[:assignment][:resumed_at] == "true"
    params[:assignment][:completed_at] = Time.now if params[:assignment][:completed_at] == "true"
  end


end

app/helpers/assignments_helper.rb
module AssignmentsHelper
	def assignment_submit_label(assignment)
		if assignment.new_record?
			return "Assign"
		else
			return "Update"
		end
	end

	def assignment_queue_index(assignment)
		assignment.queue_index || assignment.user.assignments.count + 1
	end
end

app/views/assignments/_completed_assignments.html.erb
<h3>Completed Tasks: </h3>
<% if user.completed_assignments.count > 0 %>
	<% user.completed_assignments.each do |item| %>
		<div class="completeAssignment">
			<strong><%= "#{item.task.name}: #{item.project.name}" %></strong>
			<span class="right"><em><%= "Completed: #{time_ago_in_words(item.completed_at)} ago" %></em></span>
		</div>
	<% end %>
<% else %>
	There are no completed tasks.
<% end %>

app/views/assignments/_form.html.erb
<% if @assignment %>

	<p><%= "Assigning #{@assignment.task.name} to #{@assignment.user.name} for #{@assignment.project.name}"%></p>

	<%= form_for @assignment, :remote => true do |f| %>
	<div id="assignmentErrors"></div>

	<div>
		<%= f.label :duration %>
		<%= f.text_field :duration %> hours
	</div>

	<div>
		<%= f.label :deadline %>
		<%= f.text_field :deadline, :class => "datepicker" %>
	</div>

	<div id="commentsForm">
		<%= f.fields_for :comments do |builder| %>
	    <%= render "comments/form", :f => builder %>
	  <% end %>
	</div>

	<div>
		<%= f.submit assignment_submit_label(@assignment) %>
	</div>

	<%= f.hidden_field :user_id %>
	<%= f.hidden_field :task_id %>
	<%= f.hidden_field :project_id %>
	<%= f.hidden_field :queue_index, :value => assignment_queue_index(@assignment) %>

	<% end %>
<% end %>

app/views/assignments/_index.html.erb
<h4 id="current">Current: </h4>
<%= render :partial => "assignments/show", :locals => { :assignment => user.current_assignment } %>

<% if user.on_hold.count > 0 %>
	<h4>On Hold: </h4>
	<% user.on_hold.each do |assignment| %>
		<%= render :partial => "assignments/show", :locals => { :assignment => assignment } %>
	<% end %>
<% end %>

<% if !user.queued.blank? %>
	<h4>Queue:</h4>
	<% user.queued.each do |assignment| %>
		<%= render :partial => "assignments/show", :locals => { :assignment => assignment } %>
	<% end %>
<% end %>	

app/views/assignments/_manage_header.html.erb
<span class="assignmentStatus"><em><%= assignment.status %></em></span>
<span class="assignmentQueue"><%= "Priority: #{assignment.queue_index}" %></span>
<%= link_to "x", assignment_path(assignment), :method => :delete, :confirm => "Are you sure you want to delete this assignment?", :remote => true, :class => 'right' %>
<%= link_to "edit", edit_assignment_path(assignment), :class => 'right' %>

app/views/assignments/_show.html.erb
<div class="assignmentShow" data-sort="<%= assignment.queue_index %>" data-id="<%= assignment.id %>">
	<a href="#" class="assignmentName"><%= "#{assignment.task.name}: #{assignment.project.name}" %></a>
	

	<% if params[:appendLocation] %>
		<%= render "assignments/manage_header", :assignment => assignment%>
	<% else %>
		<%= render "assignments/user_header", :assignment => assignment %>
	<% end %>


	

	<ul class="assignmentDetails">
		<li><%= "Deadline: #{parse_time(assignment.deadline) || 'None set'}" %></li>
		<li><%= "Scheduled duration: #{ assignment.duration || 'Not set'} hours" %></li>
		<li><%= "Time Spent: #{distance_of_time_in_words(assignment.elapsed_time)}"  if assignment.elapsed_time != 0 %></li>

		<% if assignment.comments.count > 0 %>
			<li class="comment">
				<%= "\"#{assignment.comments.first.content}\""%>
				</br> 
				<%= "-#{assignment.comments.first.user.name}" %>
			</li>
		<% end %>
	</ul>	
</div>

app/views/assignments/_status_link.html.erb
<% if assignment == assignment.user.current_assignment %>
	<% if assignment.status == "not yet begun" %>
		<%= link_to "Begin", assignment_path(assignment, :assignment => {:started_at => true, :resumed_at => true}), :method => 'put', :remote => true, :class => 'right' %> 
	<% elsif assignment.status == "in progress" %>
		<%= link_to "Mark Completed", assignment_path(assignment, :assignment => { :completed_at => true }), :method => 'put', :remote => true, :class => 'right' %>
		<%= link_to "Pause", assignment_path(assignment, :assignment => { :hold => true}), :method => 'put', :remote => true, :class => 'right'%>
	<% end %>
<% else %>
	
	<% if assignment.status == "on hold" && assignment.user.current_assignment.status != "in progress" %>
		<%= link_to 'resume', assignment_path(assignment, :assignment => 
				{:hold => false, :resumed_at => true}), :method => 'put', :remote => true, :class => 'right' %>
	<% end %>

<% end %>

app/views/assignments/_user_assignments.html.erb
<% if user.assigned? %>
	<%= render "assignments/index", :user => user %>
<% else %>
	<p>You currently have no assignments</p>
	<!-- <#%= link_to "Get new assignment (not active yet)", "#", :remote => true %>	 -->
<% end %>

app/views/assignments/_user_header.html.erb
<%= render 'assignments/status_link', :assignment => assignment %>	

app/views/assignments/create.js.erb
$('#task-modal').dialog( "close" );
var userId = '<%= @assignment.user.id %>';
var userSelector = 'div[data-user="' + userId + '"]';

var taskId = '<%= @assignment.task.id %>';
var taskSelector = 'div[data-task="' + taskId + '"]';

renderTaskBox(taskSelector);
renderUserBox(userSelector);

myApp.Users(userSelector).refresh();
myApp.Tasks(taskSelector).refresh();

myApp.setProjectColor();


if ( $('#userDisplay').is(':visible') ) {
	$('.queuedAssignments').html('<%= j render :partial => "assignments/index", :locals => {:user => @assignment.user } %>');
}

myApp.addAssignmentListeners();

function renderTaskBox(taskSelector) {
	$(taskSelector).replaceWith('<%= j render :partial => "tasks/show", :locals => { :task => @assignment.task, :project => @assignment.project } %>');
	myApp.draggable(taskSelector);
};

function renderUserBox(userSelector) {
	var userHtml = '<%= j render :partial => "users/box", :locals => { :user => @assignment.user } %>';
	$(userSelector).replaceWith(userHtml);
}

app/views/assignments/destroy.js.erb
$('.queuedAssignments').html('<%= j render :partial => "assignments/index", :locals => { :user => @user } %>');

var userId = '<%= @user.id %>';
var userSelector = 'div[data-user="' + userId + '"]';
var taskId = '<%= @assignment.task.id %>';
var taskSelector = 'div[data-task="' + taskId + '"]';

refreshUserBox(userSelector);
renderTaskBox(taskSelector);

myApp.Tasks(taskSelector).refresh();
myApp.Users(userSelector).refresh();

myApp.setProjectColor();


function refreshUserBox(userSelector) {
	var userHtml = '<%= j render :partial => "users/box", :locals => { :user => @user } %>';
	$(userSelector).replaceWith(userHtml);
}

function renderTaskBox(taskSelector) {
	$(taskSelector).replaceWith('<%= j render :partial => "tasks/show", :locals => { :task => @assignment.task, :project => @assignment.project } %>');
	myApp.draggable(taskSelector);
};

app/views/assignments/edit.html.erb
<div class="resourceEdit">
	<h2>Edit Assignment</h2>
	<%= render "form" %>
</div>

app/views/assignments/new.js.erb
$('#task-modal').html('<%= j render :partial => "assignments/form" %>');
$('#task-modal').dialog("open");
$( ".datepicker" ).datepicker();

app/views/assignments/update.js.erb
$('#userAssignments').html('<%= j render :partial => "assignments/user_assignments", :locals => { :user => @assignment.user } %>');
$('#completedAssignments').html('<%= j render :partial => "assignments/completed_assignments", :locals => { :user => @assignment.user } %>');
myApp.setListeners();