config/routes.rb
Trackle::Application.routes.draw do

  resources :announcements, :only => [:create, :index, :edit, :destroy, :update]
  resources :assignments, :except => [:show]
  resources :projects, :except => [:new]
  resources :tasks, :except => [:new]  
  resources :task_groups, :except => [:new, :index]
  devise_for :users
  root :to => 'schedules#show'

  devise_scope :user do
    root :to => "devise/sessions#new"
  end

  resources :users, :only => [:index, :show, :edit, :update, :destroy]
  get "/archive" => "archives#show", :as => "archives"

end

app/models/schedule.rb
class Schedule
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
	before_filter :authenticate_user!
	load_and_authorize_resource
	
	def show
		@projects = Project.where('completed_at is NULL').order('deadline')
		@project = params[:project_id] ? Project.find(params[:project_id]) : @projects.first
		@users = User.non_admin
		@announcements = Announcement.current
		if params[:time_zone]
			Time.zone = params[:time_zone]
		end
	end
	
end

app/helpers/schedules_helper.rb
module SchedulesHelper

	def task_progress_bar(task, project)
		total_assignments = task.assignments_for_project(project)
		completed_assignments = total_assignments.where('completed_at is NOT NULL')
		return "#{completed_assignments.count}/#{total_assignments.count}"
	end

	def parse_time(datetime)
		datetime.strftime("%-m/%d/%Y") if datetime
	end
end

app/views/schedules/_sidebar.html.erb
<div class="dropdown projectName" data-color="<%= @project.color if @project %>">
	<%= link_to @project.name, project_path(@project) if @project %>
	<ul class="dropdownMenu dropdownSidebar">
		<% @projects.each do |project| %>
			<li data-color="<%= project.color %>" class="dropdownProject" data-project="<%= project.id %>">
				<%= project.name %>
			</li>
		<% end %>
	</ul>
</div>


<% if @project %>
	<% if @project.tasks.any? %>
	<div>
		<% @project.tasks.each do |task| %>
			<%= render :partial => 'tasks/show', :locals => { :task => task, :project => @project } %>
		<% end %>	
	</div>
	<% else %>
		<p>There are no tasks for this project</p>
	<% end %>
<% else %>
<p>There are no projects</p>
<% end %>	

app/views/schedules/show.html.erb
<div id="project">
	<%= render 'sidebar' %>
</div>
<div id="announcementDisplay">
	<%= render 'announcements/display_index' %>
</div>

<div id="usersList">
	<% if @users.any? %>
	<div id="usersContainer">
		<% @users.each do |user| %>
			<%= render :partial => 'users/box', :locals => { :user => user } %>
		<% end %>		
	</div>
	<% end %>
</div>

<div id="task-modal" class="modal">
	<%= render 'assignments/form' %>
</div>

app/views/schedules/show.js.erb
$('#project').html('').append('<%= j render :partial => "sidebar" %>');

myApp.setDropdowns();

myApp.draggable('.draggable');

myApp.setProjectColor();

myApp.Tasks('.taskBox').refresh();